Translated faq/css-flash, faq/async-data-components, faq/cached-components
translation-gang/ru.docs.nuxtjs pull request #42
Opened 2018-02-15 16:45 UTC by xrei

#41

2018-02-16 05:55 UTC, Alex-Sokolov requested changes

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/async-data-components.md
> +Так как компоненты не имеют `asyncData` метода, вы не можете напрямую получать асинхронные данные на стороне сервера в компоненте. Для того чтобы обойти это ограничение, у вас есть два основных вариа
вы не можете напрямую получать асинхронные данные в компоненте при рендеринге на стороне сервера?

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/async-data-components.md
> +2. Сделать запрос к API в методе asyncData() или fetch() компонента страницы и передайте данные в качестве входных параметров дочерним компонентам. Рендеринг на стороне сервера будет работать нормаль
и передавать

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Для избежания шаблонного кода, используйте [Component Cache module](https://github.com/nuxt-community/modules/tree/master/packages/component-cache) для Nuxt.js. Этот модуль использует vue-server-rend
модуль Component Cache

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +- Вы **НЕ** должны кэшировать компонент, если он
просто "не" сложнее заметить, лучше "не должны" выделять жирным и капсом

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +- Вы **НЕ** должны кэшировать компонент, если он
вы не должны кэшировать компонент который

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +  - Имеет дочерние компоненты, которые могут полагаться на глобальное состояние.
имеет дочерние компоненты, зависящие от глобального состояния

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +  - Имеет дочерние компоненты, которые оказывают побочные эффекты (side effects) на `context` рендера.
имеет дочерние компоненты, вызывающие побочные эффекты ( .. ) ...

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/css-flash.md
> +Это происходит потому, что в **режиме разработки** CSS находится в javascript сборке, чтобы Webpack мог производить "горячую перезагрузку". Эта "вспышка" называется [FOUC](https://en.wikipedia.org/wi
находится в JavaScript сборки для возможности горячей перезагрузки с помощью Webpack

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/css-flash.md
> +Не переживайте, в **production режиме** CSS разделяется и помещается в заголовок, поэтому эта "вспышка" контента без стилей больше не появляется.
в заголовок страницы

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/css-flash.md
> +Не переживайте, в **production режиме** CSS разделяется и помещается в заголовок, поэтому эта "вспышка" контента без стилей больше не появляется.
больше не появится

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/duplicated-meta-tags.md
> +title: Повторяющиеся meta-теги
Дублирующиеся meta-теги

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/duplicated-meta-tags.md
> +А затем на необходимой странице:
Строка пустая пропала между текстом и примером

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/extend-webpack.md
> +     extend (config, { dev, isClient }) {
isDev ?

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/now-deployment.md
> +Чтобы развернуть с помощью [now.sh](https://zeit.co/now) в `package.json` рекомендуется следующее:
Для публикации....

2018-02-16 05:55 UTC, Alex-Sokolov commented on ru/faq/now-deployment.md
> +Заметка: мы рекомендуем добавить файл `.nuxt` в `.npmignore` или `.gitignore`.
Примечание
.nuxt это каталог со сбилженными файлами

2018-02-16 05:55 UTC, Alex-Sokolov commented
Отлично :) оставил комментарии по спорным местам

2018-02-22 15:20 UTC, Alex-Sokolov requested changes

2018-02-22 15:20 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Для избежания шаблонного кода, используйте модуль [Component Cache module](https://github.com/nuxt-community/modules/tree/master/packages/component-cache) для Nuxt.js. Этот модуль использует vue-serv
В квадратных скобках module тогда можно убрать. Перед ними модуль же

2018-02-22 15:20 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Смотрите [component-level caching](http://ssr.vuejs.org/en/caching.html#component-level-caching) для подробной информации.
Смотрите кэширование на уровне компонентов

2018-02-22 15:20 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Смотрите [component-level caching](http://ssr.vuejs.org/en/caching.html#component-level-caching) для подробной информации.
Кстати и ссылку можно тоже на русский вариант поставить

2018-02-23 07:25 UTC, Alex-Sokolov requested changes

2018-02-23 07:25 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Смотрите [component-level caching](https://ssr.vuejs.org/ru/caching.html#component-level-caching) для подробной информации.
Хэш тоже поменяться должен

2018-02-23 07:42 UTC, Alex-Sokolov commented on ru/faq/cached-components.md
> +Смотрите [component-level caching](https://ssr.vuejs.org/ru/caching.html#component-level-caching) для подробной информации.
Ну и заголовок оттуда переведённый можно использовать

2018-02-23 20:13 UTC, xrei commented on ru/faq/cached-components.md
> +Смотрите [component-level caching](https://ssr.vuejs.org/ru/caching.html#component-level-caching) для подробной информации.
Ссылка нормально работает.

2018-02-23 20:23 UTC, Alex-Sokolov approved these changes

2018-02-23 20:23 UTC, merged

2018-02-23 20:23 UTC, Alex-Sokolov commented
Спасибо! :)