api/pages-transition has been translated
translation-gang/ru.docs.nuxtjs pull request #46
Opened 2018-03-05 16:36 UTC by light4everyone

2018-03-05 19:45 UTC, Alex-Sokolov requested changes

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +> Nuxt.js использует компонент [`<transition>`](https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components), чтобы позволить вам создавать поразительные переходы/анимации ме
Ссылку на русскую версию документации надо поменять (и с хэшем правильным на русскую поставить)

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +> Nuxt.js использует компонент [`<transition>`](https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components), чтобы позволить вам создавать поразительные переходы/анимации ме
И вроде пробел после точки ещё лишний

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +- **Type:** `String` или `Object` или `Function`
Тип можно перевести :)

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +Чтобы установить пользовательский переход для определенного пути, просто добавьте ключ `transition` к компонент странице.
к компоненту страницы

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +Если ключ `transition` задан как строка, то он будет использоваться как `transition.name`.
задан строкой, то он будет использован как

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +| `mode`             | `String`  | `"out-in"`   | Режим перехода, применяемое ко всем путям, смотрите [Vue.js документацию](https://vuejs.org/v2/guide/transitions.html#Transition-Modes)
Ссылки на русскую документацию надо проставить

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +| `enterClass`       | `String`  | n/a          | Начальное состояние пользовательского класса перехода. Смотрите [Vue.js документацию](https://vuejs.org/v2/guide/transitions.html#Custom-Transition-C
Смотрите [документацию Vue] — будет звучать получше

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +*Примечание: Также рекомендуется добавить `css: false` для JavaScript-only переходов, чтобы Vue мог пропускать CSS обнаружение. Это также предотвращает случайное вмешательство CSS правил в переход.*
для JavaScript-переходов

2018-03-05 19:45 UTC, Alex-Sokolov commented on ru/api/pages-transition.md
> +*Примечание: Также рекомендуется добавить `css: false` для JavaScript-only переходов, чтобы Vue мог пропускать CSS обнаружение. Это также предотвращает случайное вмешательство CSS правил в переход.*
чтобы Vue пропускал определение CSS

2018-03-05 19:46 UTC, Alex-Sokolov commented
Спасибо за PR! :) поправьте по комментариям

2018-03-05 20:33 UTC, light4everyone commented
Поправки внесены. Рад стараться! :)

2018-03-06 08:26 UTC, Alex-Sokolov approved these changes

2018-03-06 08:26 UTC, merged