Update configuration-loading.md
translation-gang/ru.docs.nuxtjs pull request #53
Opened 2018-10-25 06:02 UTC by severin-d

2018-10-25 19:27 UTC, Alex-Sokolov requested changes

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +title: "API: войство loading"
буква пропала

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +description: Nuxt.js использует свой компонент для отображения процесса загрузки страницы или маршрута. Вы можете изменить его, отключить или создать свой собственный компонент загрузки.
или создать свой собственный. И хватит, повторяться не стоит

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Nuxt.js использует свой компонент для отображения процесса загрузки страницы или маршрута. Вы можете изменить его, отключить или создать свой собственный компонент загрузки.
и тут

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +> Nuxt.js использует свой компонент для отображения процесса загрузки страницы или маршрута. Вы можете изменять его, отключить или создать свой собственный компонент загрузки.
Три раза повторяются что ли?

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +| `color` | Строка | `'black'` | Цвет индикатора |
Строку тут не надо было переводить, везде типы не переводим же

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +| `height` | Строка | `'2px'` | Высота полосы (Используется в свойстве `style`) |
внутри скобок не нужно с большой

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Например, чтобы сделать синий индикатор загрузки и 5 пикселями высоты, мы добавим в `nuxt.config.js` следующее:
высотой в 5 пикселей

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Вы можете создать свой компонент загрузки, который Nuxt.js будет вызывать вместо стандартного. Чтобы сделать это, нужно указать путь к внему в свойстве `loading`. Теперь Nuxt.js будет вызывать его ав
"внему" опечатка

2018-10-25 19:27 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +| `start()` | Обязательный | Вызывается при изменении маршрута. Показывает индикатор |
Обязателен / Опциональный

2018-10-25 19:27 UTC, Alex-Sokolov commented
Спасибо за новый перевод :)

2018-10-25 19:35 UTC, severin-d commented on ru/api/configuration-loading.md
> +> Nuxt.js использует свой компонент для отображения процесса загрузки страницы или маршрута. Вы можете изменять его, отключить или создать свой собственный компонент загрузки.
Третий раз действительно был случайным, не доглядел.

2018-10-25 19:39 UTC, Alex-Sokolov requested changes

2018-10-25 19:39 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +description: Nuxt.js использует свой компонент для отображения процесса загрузки страницы или маршрута. Вы можете изменить его, отключить или создать свой собственный компонент загрузки.
Создать свой собственный и ок, как ниже написано

2018-10-25 19:39 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Чтобы индикатор загрузки не показывался при загрузке страниц, добавьте `loading: false` в `nuxt.config.js`:
Прилипло

2018-10-25 19:43 UTC, severin-d commented on ru/api/configuration-loading.md
> +Чтобы индикатор загрузки не показывался при загрузке страниц, добавьте `loading: false` в `nuxt.config.js`:
Не очень понял что именно  😞

2018-10-26 21:15 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Чтобы индикатор загрузки не показывался при загрузке страниц, добавьте `loading: false` в `nuxt.config.js`:
Строка пропала и с примером слиплось. Но вроде теперь ок

2018-10-26 21:16 UTC, Alex-Sokolov requested changes

2018-10-26 21:16 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
> +Вы можете создать свой компонент загрузки, который Nuxt.js будет вызывать вместо стандартного. Чтобы сделать это, нужно указать путь к нему в свойстве `loading`. Теперь Nuxt.js будет вызывать его авт
Лишняя строка выше появилась

2018-10-26 21:16 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
>  | Method | Required | Description |
Перевода заголовка таблицы нет

2018-10-29 13:48 UTC, severin-d commented on ru/api/configuration-loading.md
>  | Method | Required | Description |
>Your component has to expose some of these methods
> > Ваш компонент должен содержать следующие методы

Так есть же

2018-10-29 17:23 UTC, Alex-Sokolov commented on ru/api/configuration-loading.md
>  | Method | Required | Description |
| Method | Required | Description |

2018-10-30 08:27 UTC, Alex-Sokolov approved these changes

2018-10-30 08:28 UTC, merged

2018-10-30 08:28 UTC, Alex-Sokolov commented
Спасибо!